# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('usage', models.CharField(max_length=100)),
                ('card_number', models.IntegerField()),
                ('total_capacity', models.FloatField()),
                ('data_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['cid'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('work_city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minieye_data.Manager'),
        ),
    ]
