# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minieye_data', '0002_auto_20160819_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
    ]
